# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28580c76cdeb43e7099f77125367aec95e1f131fac506fb7cfd5faaf0710bc26f011c55026bda0729f6796ef98f168bde85470ec9c6b63d827e22a8033376262

test:
  secret_key_base: 6049c87147fe69b6f928849d010339b5d596955b84408543550260317b413c9e7baba058b900bdb404d56e0da2dc3e37e74cfae1ecc889fbdf4e719dee48a0df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
